export const countries = [
  { name: "United States", code: "US", currency: "USD", symbol: "$" },
  { name: "United Kingdom", code: "GB", currency: "GBP", symbol: "£" },
  { name: "European Union", code: "EU", currency: "EUR", symbol: "€" },
  { name: "Japan", code: "JP", currency: "JPY", symbol: "¥" },
  { name: "Australia", code: "AU", currency: "AUD", symbol: "A$" },
  { name: "Canada", code: "CA", currency: "CAD", symbol: "C$" },
  { name: "Switzerland", code: "CH", currency: "CHF", symbol: "CHF" },
  { name: "China", code: "CN", currency: "CNY", symbol: "¥" },
  { name: "India", code: "IN", currency: "INR", symbol: "₹" },
  { name: "Singapore", code: "SG", currency: "SGD", symbol: "S$" },
  { name: "Hong Kong", code: "HK", currency: "HKD", symbol: "HK$" },
  { name: "New Zealand", code: "NZ", currency: "NZD", symbol: "NZ$" },
  { name: "Sweden", code: "SE", currency: "SEK", symbol: "kr" },
  { name: "Norway", code: "NO", currency: "NOK", symbol: "kr" },
  { name: "Denmark", code: "DK", currency: "DKK", symbol: "kr" },
  { name: "South Korea", code: "KR", currency: "KRW", symbol: "₩" },
  { name: "Brazil", code: "BR", currency: "BRL", symbol: "R$" },
  { name: "Mexico", code: "MX", currency: "MXN", symbol: "$" },
  { name: "South Africa", code: "ZA", currency: "ZAR", symbol: "R" },
  { name: "United Arab Emirates", code: "AE", currency: "AED", symbol: "د.إ" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", symbol: "﷼" },
  { name: "Turkey", code: "TR", currency: "TRY", symbol: "₺" },
  { name: "Russia", code: "RU", currency: "RUB", symbol: "₽" },
  { name: "Poland", code: "PL", currency: "PLN", symbol: "zł" },
  { name: "Thailand", code: "TH", currency: "THB", symbol: "฿" },
  { name: "Malaysia", code: "MY", currency: "MYR", symbol: "RM" },
  { name: "Indonesia", code: "ID", currency: "IDR", symbol: "Rp" },
  { name: "Philippines", code: "PH", currency: "PHP", symbol: "₱" },
  { name: "Vietnam", code: "VN", currency: "VND", symbol: "₫" },
  { name: "Argentina", code: "AR", currency: "ARS", symbol: "$" },
  { name: "Chile", code: "CL", currency: "CLP", symbol: "$" },
  { name: "Colombia", code: "CO", currency: "COP", symbol: "$" },
  { name: "Peru", code: "PE", currency: "PEN", symbol: "S/" },
  { name: "Egypt", code: "EG", currency: "EGP", symbol: "£" },
  { name: "Nigeria", code: "NG", currency: "NGN", symbol: "₦" },
  { name: "Kenya", code: "KE", currency: "KES", symbol: "KSh" },
  { name: "Israel", code: "IL", currency: "ILS", symbol: "₪" },
  { name: "Czech Republic", code: "CZ", currency: "CZK", symbol: "Kč" },
  { name: "Hungary", code: "HU", currency: "HUF", symbol: "Ft" },
  { name: "Romania", code: "RO", currency: "RON", symbol: "lei" },
  { name: "Pakistan", code: "PK", currency: "PKR", symbol: "₨" },
  { name: "Bangladesh", code: "BD", currency: "BDT", symbol: "৳" },
  { name: "Sri Lanka", code: "LK", currency: "LKR", symbol: "Rs" },
  { name: "Taiwan", code: "TW", currency: "TWD", symbol: "NT$" },
  { name: "Iceland", code: "IS", currency: "ISK", symbol: "kr" },
  { name: "Croatia", code: "HR", currency: "EUR", symbol: "€" },
  { name: "Ukraine", code: "UA", currency: "UAH", symbol: "₴" },
  { name: "Morocco", code: "MA", currency: "MAD", symbol: "د.م." },
  { name: "Qatar", code: "QA", currency: "QAR", symbol: "﷼" },
  { name: "Kuwait", code: "KW", currency: "KWD", symbol: "د.ك" },
]
